Implement RFC8693 Token Exchange Request
jumbojett/OpenID-Connect-PHP pull request #275
Opened 2021-09-14 15:03 UTC by IljaN

**List of common tasks a pull request require complete**
- [ ] Changelog entry is added or the pull request don't alter library's functionality

2021-09-14 17:46 UTC, DeepDiver1975 requested changes

2021-09-14 17:46 UTC, DeepDiver1975 commented on src/OpenIDConnectClient.php
> +        $token_endpoint = $this->getProviderConfigValue('token_endpoint');
Wouldn't apply the client_secret_basic auth_method here as well?

```
        # Consider Basic authentication if provider config is set this way
        if (in_array('client_secret_basic', $token_endpoint_auth_methods_supported, true)) {
            $headers = ['Authorization: Basic ' . base64_encode(urlencode($this->clientID) . ':' . urlencode($this->clientSecret))];
            unset($token_params['client_secret']);
	    unset($token_params['client_id']);
        }

2021-11-29 08:24 UTC, DeepDiver1975 requested changes
- [ ] update changelog please
- [ ] did you rebase? CI is not executed ....

2022-04-09 23:20 UTC, Ninja-mann approved these changes

2022-07-08 11:04 UTC, merged